repos:
-   repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: uv run ruff check
        language: python
        types: [python]
        args: [--select, I, --fix]
      - id: ruff-format
        name: ruff-format
        entry: uv run ruff format
        language: python
        types: [python]
-   repo: local
    hooks:
    - id: interrogate
      name: interrogate
      entry: uv run interrogate
      language: system
      types: [python]
      args: [src, -v, -i]